# Generated by Django 6.0.1 on 2026-04-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapi', '0002_userprofile_credit_score_userprofile_is_free_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrim',
            name='bounty',
            field=models.IntegerField(default=0),
        ),
    ]
