# Generated by Django 6.0.1 on 2026-04-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapi', '0003_scrim_bounty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='is_active',
        ),
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_free_to_join',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize_pool',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('coming_soon', 'Coming Soon'), ('open', 'Open'), ('live', 'Live'), ('completed', 'Completed')], default='open', max_length=16),
        ),
    ]
