# Generated by Django 6.0.1 on 2026-04-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapi', '0004_remove_tournament_is_active_tournament_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='guild_only',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_slots',
            field=models.IntegerField(choices=[(8, 8), (16, 16), (32, 32), (64, 64)], default=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_lane',
            field=models.CharField(blank=True, choices=[('Jungle', 'Jungle'), ('Mid', 'Mid'), ('Gold', 'Gold'), ('EXP', 'EXP'), ('Roam', 'Roam')], max_length=32),
        ),
    ]
