# Generated by Django 6.0.1 on 2026-04-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapi', '0006_guild_is_private_guild_level_guild_max_slots_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='guild',
        #     name='country',
        #     field=models.CharField(blank=True, max_length=64),
        # ),
        # migrations.AddField(
        #     model_name='guild',
        #     name='join_policy',
        #     field=models.CharField(choices=[('Open', 'Open'), ('Request', 'Request Only'), ('Password', 'Password Protected')], default='Open', max_length=32),
        # ),
        # migrations.AddField(
        #     model_name='guild',
        #     name='tag',
        #     field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        # ),
    ]
