# Generated by Django 6.0.1 on 2026-04-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapi', '0007_guild_country_guild_join_policy_guild_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='guild_a_checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='guild_b_checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='result_image',
            field=models.ImageField(blank=True, null=True, upload_to='results/'),
        ),
        migrations.AddField(
            model_name='match',
            name='room_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='match',
            name='room_password',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='tournament',
            name='check_in_window',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize_pool_distribution',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rules',
            field=models.TextField(blank=True),
        ),
    ]
