# Generated by Django 6.0.1 on 2026-04-30 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapi', '0008_match_guild_a_checked_in_match_guild_b_checked_in_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentteam',
            name='main_players',
            field=models.ManyToManyField(blank=True, related_name='tournament_main_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentteam',
            name='sub_players',
            field=models.ManyToManyField(blank=True, related_name='tournament_sub_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HeroBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_name', models.CharField(max_length=64)),
                ('ban_count', models.IntegerField(default=1)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_bans', to='mlapi.tournament')),
            ],
        ),
    ]
