# Generated by Django 6.0.1 on 2026-04-30 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapi', '0009_tournamentteam_main_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bans_a',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='match',
            name='bans_b',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='match',
            name='hype_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='picks_a',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='match',
            name='picks_b',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='team_a_gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team_a_kills',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b_gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b_kills',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PrizeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rank', models.IntegerField()),
                ('distributed_at', models.DateTimeField(auto_now_add=True)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlapi.guild')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize_history', to='mlapi.tournament')),
            ],
        ),
    ]
